### ISSUE TITLE
update info.xml screenshot

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/market#102]
![owncloud-marketapp](https://user-images.githubusercontent.com/16665512/27691141-75c890f8-5ce3-11e7-9886-91e5a4994e19.jpg)

**Comment by felixheidecke** [comment]
This screenshot is old and the quality is pretty low.

**Comment by felixheidecke** [comment]
How about: https://raw.githubusercontent.com/owncloud/screenshots/master/market/market-app_0.2.0.png

**Comment by hurradieweltgehtunter** [comment]
Screenshot is taken from current version of market app. If you want to change it:
- 1400px wide, 2:1 ratio
- show enterprise apps
- name it to ownCloud-market-app.jpg
- use jpg
last 2 points are marketplace SEO reasons

**Comment by felixheidecke** [comment]
https://raw.githubusercontent.com/owncloud/screenshots/master/market/ownCloud-market-app.jpg

**Comment by hurradieweltgehtunter** [comment]
fine with me

**Comment by DeepDiver1975** [comment]
fixed with f8d6c92830f474268e063ea43f3ec1ed3a23d861
