### ISSUE TITLE
Check market app with core Guzzle7

### ISSUE THREAD

**Issue by phil-davis** [owncloud/market#1043]
Install the current core master (which will be 10.11) and current market app code.

Check that market operations can be done to the real marketplace:

- market:install                
- market:list                   
- market:uninstall              
- market:upgrade

Related to issue https://github.com/owncloud/core/issues/39387

**Comment by kiranadh1452** [comment]
- market:install :heavy_check_mark: 
- market:list :heavy_check_mark:              
- market:uninstall :heavy_check_mark: 
- market:upgrade :heavy_check_mark:
