### ISSUE TITLE
Uninstalling market app from market should go to files view and refresh page.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#113]
### Steps to reproduce

0. Having a server with market app installed and enabled.
1. Using admin user go to market.
2. Search for market app.
3. Uninstall it.

### Expected behaviour
It shows the message the app has been uninstalled correctly and goes back to the files view, refreshing the page and making unable to keep using market.

### Actual behaviour
No refresh. You can still keep using market seeing things fail.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Comment by DeepDiver1975** [comment]
solution: disallow uninstall of market app in market app

**Comment by DeepDiver1975** [comment]
aka disable-suicide-mode
