### ISSUE TITLE
Enterprise trial button is not clickable after adding API key.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#114]
### Steps to reproduce

0. Having a server already installed.
1. Using admin user go to market.
2. Follow the steps in https://marketplace.owncloud.com/enterprise-trial (skip 1).
Which are:
     2.1 Go to the market app inside your ownCloud. Click on „Add API key“ and paste your personal API key.
     2.2 In the Market App, click the "Start Enterprise Trial" button and install the Enterprise Apps.

### Expected behaviour
After adding the API key, the enterprise trial button is enabled and clickable .

### Actual behaviour
the enterprise button is disabled.

Correctly added api key:
![screen shot 2017-07-17 at 10 33 05](https://user-images.githubusercontent.com/9048796/28260689-8e7a805a-6adc-11e7-8f90-5a4df5fe341c.png)

But button is disabled:
![screen shot 2017-07-17 at 10 33 12](https://user-images.githubusercontent.com/9048796/28260700-937f6264-6adc-11e7-9f55-90953cd1c14b.png)

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocl5zfuijvrr',
  'passwordsalt' => 'HIDDEN',
  'secret' => 'HIDDEN',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'HIDDEN',
  ),
  'datadirectory' => '/opt/owncloud/data',
  'overwrite.cli.url' => 'http://HIDDEN',
  'dbtype' => 'mysql',
  'version' => '10.0.2.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_admin',
  'dbpassword' => 'HIDDEN',
  'logtimezone' => 'UTC',
  'installed' => true,
  'license-key' => 'HIDDEN',
  'ldapIgnoreNamingRules' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

cc: @hurradieweltgehtunter

**Comment by felixheidecke** [comment]
The *The content of config/config.php:* section is empty.

**Comment by SergioBertolinSG** [comment]
Added.

**Comment by felixheidecke** [comment]
Got your problem right here: `'license-key' => 'HIDDEN'`.
You already have a license key set and if so, you can't get a new demo key.

**Comment by SergioBertolinSG** [comment]
As easy as that, sorry for the noise.

**Comment by SergioBertolinSG** [comment]
After removing the license-key from the config.php file and clicking the start enterprise trial, I didn't get a new license-key in the config.php file. Should it be added there? It said in the UI the trial had start.

**Comment by SergioBertolinSG** [comment]
The enteprise_key app should be installed and enabled automatically when starting the trial ?
