### ISSUE TITLE
Installing enterprise apps is not possible using CLI.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#115]
### Steps to reproduce

1. Have enterprise_key app installed and a valid license in config.php.
2. Do occ market:install windows_network_drive (for example, any EE app can be used).

### Expected behaviour
I see two options:

1. Enterprise apps are correctly installed in the case of having enterprise key app and a valid license.
or
2. Market app won't allow to install enterprise apps via CLI. In this case those apps should not appear in the market:list command.

### Actual behaviour
In the market:list command we can see all the enterprise edition apps available.
After installing:
windows_network_drive: Installing new app ...
windows_network_drive: No marketplace connection

(The message is not correct as the connection with the marketplace works when installing CE apps).

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

@pmaier1 What should be the expected behaviour?
cc: @hurradieweltgehtunter

**Comment by SergioBertolinSG** [comment]
This commands work when following the enterprise trial process.

**Comment by pmaier1** [comment]
Did you add your marketplace API key before trying to install the enterprise apps?

**Comment by SergioBertolinSG** [comment]
No, without API key. Adding it, it works fine.

**Comment by pmaier1** [comment]
Inserting the API key into an instance is mandatory to "connect" with the marketplace and get access to the enterprise apps. Free apps are available without API key.

**Comment by SergioBertolinSG** [comment]
Ok thanks @pmaier1 , then we'll need to add it when creating the server:
https://github.com/owncloud/market/issues/124
