### ISSUE TITLE
Visual problems when using Internet Explorer 11.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#119]
The loading spinner of the install buttons is not well positioned:

![screen shot 2017-07-17 at 15 22 19](https://user-images.githubusercontent.com/9048796/28269938-06be1af0-6b04-11e7-94de-c6e5a09eedec.png)

The dialog box warning you about an app uninstallation is not centered:

![screen shot 2017-07-17 at 15 21 52](https://user-images.githubusercontent.com/9048796/28269941-0b70f130-6b04-11e7-81f4-073fde2c796e.png)

cc: @felixheidecke

**Comment by PVince81** [comment]
moving to "planned" for the next release

**Comment by felixheidecke** [comment]
I can not confirm this behavior in the current master 😲

**Comment by felixheidecke** [comment]
@SergioBertolinSG can you have a look if this has been fixed in master?

**Comment by SergioBertolinSG** [comment]
Yes, it no longer happens in master.
