### ISSUE TITLE
Market app doesn't interact correctly with apps coming in the enterprise tarball.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#121]
### Steps to reproduce

0. Have an enterprise edition server installed from tarball with a valid license key.
1. Check for app updates on the market app.
2. Check if enterprise apps are installed on market.

### Expected behaviour
1. Enterprise apps can be updated from marketplace.
2. Enterprise apps coming from tarball are detected as installed.

### Actual behaviour
1. When trying to update enterprise apps I get "No marketplace connection"
2. Disabled enteprise apps coming from tarball are not detected as installed. (I guess because they are disabled but installed != enabled).

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

@felixboehm the importance of this bug depends on our interest on keep providing enterprise tarballs.

**Comment by patrickjahns** [comment]
Updating enterprise applications via the marketplace requires a valid/active subscription on the marketplace.

**Comment by patrickjahns** [comment]
Proper error messages for upgrading enterprise apps without a valid subscriptions should now be handled by #141 

@SergioBertolinSG 
can you clarify what you mean by apps are disabled?

**Comment by SergioBertolinSG** [comment]
This issue is just a confusion. When testing this I didn't know the API key was needed, the message wasn't very clear about what was missing. Closing.
