### ISSUE TITLE
Workflow app is not available in the enterprise bundle.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#122]
@felixboehm will it be included soon?

If it is this way because some decision I'm not aware of, please close.

**Comment by DeepDiver1975** [comment]
here we go: https://marketplace.owncloud.com/apps/workflow

**Comment by DeepDiver1975** [comment]
but is not part of the bundle @hurradieweltgehtunter how can we fix this? THX

**Comment by hurradieweltgehtunter** [comment]
1) edit the description text, remove wrong indents to remove pre-formatted text
2) add entry in table "bundle_products": product_id: 40, bundle_id: 35

should be it

**Comment by DeepDiver1975** [comment]
> edit the description text, remove wrong indents to remove pre-formatted text

https://github.com/owncloud/workflow/pull/124

**Comment by DeepDiver1975** [comment]
> add entry in table "bundle_products": product_id: 40, bundle_id: 35

done
