### ISSUE TITLE
market app update doesn't work

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/market#123]
Just happened in a support call with a customer:
- Market app v0.1.0 shows n available update (v.0.2.1)
- click on update
- update runs
- feedback "Update successful"
- version still 0.1.0, still shows "available update 0.1.0 -> 0.2.1"

**Comment by LukasReschke** [comment]
Love how you publicly disclosed customer data here 🚀

**Comment by hurradieweltgehtunter** [comment]
@patrickjahns solved this: it's about write permissions.
User should be notified about this

**Comment by patrickjahns** [comment]
I have come across similar issues when updating applications via the marketplace in general. 

We attempt an update, but never check if the updater actually has permissions to write. 
What happen is:
- the marketplace app attempts the update
- the webserver user has no write permissions and silently fails
- the market app verifies the update (it sees an application at the destination folder) and falsely notifies the user that the update was successfull (while infact nothing happened)
- the marketplace app interface reloads and shows the old version.

Ideas:
- have a preUpdate process/hook that will check if the application folder is actually writable for the webserver user (and notify the user if it does not?)
- have a verification Step that checks if the new app version is the expected app version ?

**Comment by DeepDiver1975** [comment]
If the app folder is not writable (which is already checked in core) the market app has to refuse it's operations with respect to trying to update or install.

 Browsing might still be okay to operate as usual. 

This mechanism is critical to clustered setups. We need to disallow market operations in such setups. As minster need to properly deploy apostle to their cluster servers.

**Comment by patrickjahns** [comment]
Not sure if I understood you correctly? The mechanism is already there and not working? Or the marketapp needs to call a specific core api to check beforehand?

**Comment by patrickjahns** [comment]
@DeepDiver1975 
is this closed by #125 ?

**Comment by Blindfreddy** [comment]
Same problem here, resolved by modifying the permissions of the contents of folder owncloud/apps so that the webserver user www-data has rw privileges.  For some reason the files were partially owned by root with group root. Suggested fix is to add a stat command before updating and report an error if www-data has no write permissions.
