### ISSUE TITLE
Add command in occ to set the marketplace API key

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#124]
The only way to introduce the marketplace API key right now is by using the web ui.

This is a problem when creating a new enterprise server automatically.

So, I suggest to add a command in occ to introduce it. This will improve our testing of enterprise apps.

cc @pmaier1 @hurradieweltgehtunter

**Comment by pmaier1** [comment]
You can just add it to config.php or create a separate license.config.php. Probably that's not yet documented. Adding an occ command might make it easier nevertheless.

**Comment by SergioBertolinSG** [comment]
Ah, that would be enough for our servers.

**Comment by DeepDiver1975** [comment]
you can also set it in the app config ... https://github.com/owncloud/market/blob/master/lib/MarketService.php#L413-L417
