### ISSUE TITLE
Marketplace API Key submit not working

### ISSUE THREAD

**Issue by tobiherr** [owncloud/market#129]
Tried to submit the Marketplace API Key to my oC instance within the Market App. Clicked on "Save", nothing happend. Tried it multiple times, also generated a new Marketplace API key, no result. Therefore no connection between Market App and Marketplace possible --> no starting of Enterprise Trial possible

![bildschirmfoto 2017-08-01 um 18 14 09](https://user-images.githubusercontent.com/11944538/28835333-4958a758-76e5-11e7-8f2c-9eae041cd1e6.png)
After clicking on "Save" nothing happens.

**Comment by felixboehm** [comment]
1. setup appliance
2. update market app
3. start trial -> add api-key

works. can't reproduce.

**Comment by patrickjahns** [comment]
Will close this since we can not reproduce and no further logs provided
