### ISSUE TITLE
App panel borders too light on some screens

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#132]
Picture made with mobile phone, this is how it looks on my screen:

![img_20170815_111946](https://user-images.githubusercontent.com/277525/29309906-f5104cc4-81ab-11e7-90d7-98342c63eddb.jpg)

The border is too light which makes it difficult to find out which text matches with which box.

@felixheidecke @pmaier1

**Comment by felixheidecke** [comment]
That's an easy fix. Should we move that to development?

**Comment by PVince81** [comment]
@felixheidecke sounds good
