### ISSUE TITLE
[QA] market app fails to show in web UI with some versions of windows edge browser

### ISSUE THREAD

**Issue by jnweiger** [owncloud/market#1367]
Seen with oc10.14.0 and market-0.9.0-rc.1 and Microsoft Edge 44.17763,1,0 Microsoft EdgeHTML 18.17763
Running on Windows Version	10.0.17763 Build 17763

* Install market-0.9.0-rc.1 on oc10.14.0
* Log in as admin, open task switcher, click on market.
* A blank page appears: BAD

![grafik](https://github.com/owncloud/market/assets/1108546/9c13ecff-42d5-4d74-9304-35ca7b3b7236)

----

* the F12 browser console has complaints about string or integer in the javascript code.
* `SCRIPT1028: Expected identifier, string or number          market.bundle.js (2,412896)`

![grafik](https://github.com/owncloud/market/assets/1108546/942988d3-3c74-4566-821b-51dfeafaa2d7)

**Comment by jnweiger** [comment]
Workaround:
* downgrade to market-0.8.0

**Comment by DeepDiver1975** [comment]
Which compatibility mode?

**Comment by jnweiger** [comment]
In later versions of edge, I can find something about a compatibilitiy mode:
![grafik](https://github.com/owncloud/market/assets/1108546/8f667a5e-c8a3-4ddb-bebe-626f2022cbaa)

---
Regarding the specific edge vrsion, I am testing with, I cannot find a compatibility mode there. 
Chatgpt seems to confirm that:

Microsoft Edge version 44.17763.1.0 with EdgeHTML 18.17763 is the legacy version of Microsoft Edge, which does not support Internet Explorer mode. Internet Explorer mode is available in the Chromium-based version of Microsoft Edge, which was released starting in January 2020.

**Comment by jnweiger** [comment]
The EdgeHTML rendering engine does not seem to support some of the new JS that we now use.

**Comment by DeepDiver1975** [comment]
THX. Looks like I need to tweak webpack....

**Comment by jnweiger** [comment]
Maybe this legacy version of edge is sufficently depecated and not worth suppporting. I followed some of the msn click bait and the pages don't render, due to the very same javascript error.

**Comment by DeepDiver1975** [comment]
> Microsoft Edge 44.17763,

seriously - latest edge is 125
