### ISSUE TITLE
FR: show that there are app updates available in regular files view for admin. 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/market#139]
Current behaviour: 

Admin logs in and has the regular files view. 
He has no notification that there are updates for apps.

Only if he goes into the market app, there is an notification about app updates. 

Expected behaviour:
When admin logs in he has some sort of notification about available updates even in the files view.

**Comment by DeepDiver1975** [comment]
This is already implemented in market - https://github.com/owncloud/market/pull/108

needs a release afaik
