### ISSUE TITLE
App version shown in market is the already installed one instead of the latest, even when today's date is shown

### ISSUE THREAD

**Issue by davitol** [owncloud/market#144]
Using oC stable10 tarball

![screen shot 2017-09-06 at 09 50 05](https://user-images.githubusercontent.com/10596560/30100474-4e79ea06-92e9-11e7-9504-6c9a6816a698.png)

![screen shot 2017-09-06 at 09 47 28](https://user-images.githubusercontent.com/10596560/30100487-54df5db8-92e9-11e7-9af8-5f2a6349d207.png)

**Comment by patrickjahns** [comment]
Can you please clarify what the issue in this matter is?

**Comment by davitol** [comment]
IMHO the app version that should be shown in the second screenshot is the one we are going to update (the higher one) not the already installed. If I haven't explained properly just ping me again.

**Comment by patrickjahns** [comment]
Thanks for clarification - if you click on update - the version installed is the correct one right?

**Comment by patrickjahns** [comment]
@felixheidecke 

Can you have a look if this is just a frontend matter, or if you require anything else from the market app?

**Comment by davitol** [comment]
> Thanks for clarification - if you click on update - the version installed is the correct one right?

Yes it is

**Comment by felixheidecke** [comment]
@patrickjahns the **created** key in `installInfo: {}` is missing, so it just displays today's date. Not sure if it was present in an earlier version?

**Comment by patrickjahns** [comment]
I just checked - we do not save the date of the release locally, so that is the reason why in `installInfo: {}` the date is missing. 

Can we maybe show in that window something among the lines of:

```
Currently Installed version: 1

Update available to version: 2 (releasedate) 
```

**Comment by felixheidecke** [comment]
Hmmm … that creates an inconsistency in the UX. It raises the question if the date is necessary at all. If not, we can drop it.
