### ISSUE TITLE
[UI] requirement for the front end

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/market#15]
# What do we want to display?
- list of purchased apps
- list of free apps
- list of installed apps (those can be enabled or disabled)
- each list offers categories for splitting the list into pieces

# What does a user want to do?
- install an app (free or purchase)
- uninstall an app
- enable and disable an app
- each app list should support filtering
- upload an app package - necessary for instances which have no internet access

# What information is available for an app?

here is an example of the information as comminicated to to owncloud 9.1 between fe and be - we will change this structure. take this as an idea ...
```json
     {
         "missingDependencies" : [],
         "internal" : 0,
         "label" : "",
         "id" : "174779",
         "author" : "netknights",
         "typename" : "ownCloud Productivity",
         "dependencies" : {
            "owncloud" : {
               "@attributes" : {
                  "min-version" : "9.1.4.2",
                  "max-version" : "9.1.4.2"
               }
            }
         },
         "active" : false,
         "missingMinOwnCloudVersion" : false,
         "version" : "2.2.0",
         "preview-full" : "https://apps.owncloud.com/CONTENT/content-pre1/174779-1.png",
         "personid" : "netknights",
         "license" : "AGPL",
         "update" : false,
         "ocs_id" : "174779",
         "licence" : "AGPL",
         "groups" : [],
         "name" : "privacyIDEA ownCloud App",
         "detailpage" : "https://apps.owncloud.com/content/show.php?content=174779",
         "missingMaxOwnCloudVersion" : false,
         "preview" : "https://apps.owncloud.com/CONTENT/content-m1/m174779-1.png",
         "score" : "53",
         "description" : "Flexible, enterprise ready two factor authentication\n\nThis app helps you secure the access to the ownCloud Web UI in your company. It adds a second factor to the Web UI login. This second factor can be any Smartphone App, key fob tokens, smartdisplayer cards, SMS or Email, Yubikey or the Nitrokey and all common OTP tokens.\n\nThe authentication devices are manages centrally in the privacyIDEA server. Running one privacyIDEA server in your network enables you to add second factor not only to your ownCloud installation but also to any other application like web portals, firewall, VPN, Windows Desktop login, SSH servers...\n\nThe privacyIDEA ownCloud Application runs in a demo mode after download and installation. You need a working privacyIDEA installation and a subscription file provided by NetKnights for productive use.\n\nNote: After activating the App *all* users will be verified with a second factor. I.e. be sure to have your privacyIDEA server up and running and to configure the privacyIDEA ownCloud App correctly.\n\nWe recommend that you first get a basic understanding of the privacyIDEA server!\n\nSee the youtube video to get an idea https://www.youtube.com/watch?v=Lgum_cTY_Y8&amp;t=21s how this works.",
         "canUnInstall" : false,
         "changed" : 1486019868,
         "needsDownload" : true,
         "removable" : false,
         "profilepage" : "http://opendesktop.org/usermanager/search.php?username=netknights",
         "type" : "922",
         "canInstall" : true,
         "downloads" : 291,
         "level" : 100
      },

**Comment by PVince81** [comment]
add checkboxes and tickets to track progress ?

**Comment by felixheidecke** [comment]
Better move those to a project instead of using an *issue* (deutsch = Problem) for tasks?!

**Comment by PVince81** [comment]
you'll still need to raise issues for every tasks and put them into a github project

**Comment by PVince81** [comment]
I'm reopening this so it doesn't get lost.

Please close once you have the project/issue/replacement ready.

**Comment by PVince81** [comment]
(and a link that points to it)

**Comment by felixheidecke** [comment]
This is the FE Projects board: https://github.com/owncloud/market/projects/1
And here are general specifications https://github.com/owncloud/market/wiki/Project-Specifications

**Comment by PVince81** [comment]
I see you used notes, but it's not possible to comment on them. Advantage of tickets is that we can discuss in them. But whatever, I'll let you take care of managing this.

**Comment by PVince81** [comment]
Can I freely add stuff to your project list ? Normally I'd raise new issues.
Here are some items:
- search box
- "update all apps" button

If I do there is no chance to discuss about how to implement them. Where do you want to discuss these things and keep track of the discussion ? (not a chat as the discussion and reasoning will be lost in time)
