### ISSUE TITLE
Show new releases and new apps even if not installed

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/market#150]
Today the admin is only notified if there is an app update.

It would be great to show new apps and new app releases for not installed apps as well.

maybe just a menu entry on the left like "New apps" or something

**Comment by DeepDiver1975** [comment]
guilty code: https://github.com/owncloud/marketplace/blob/c24b046d4dc89f0addd8757f8c8e890d8ff8aee9/src/AppBundle/Service/MinioService.php#L96-L111

**Comment by DeepDiver1975** [comment]
guilty pr: https://github.com/owncloud/marketplace/pull/182

**Comment by DeepDiver1975** [comment]
@IljaN please have a look - thx

**Comment by felixheidecke** [comment]
Can you sketch out how this should look and work? Right now, I don't see a case for this outside of an opt-in newsletter or something. That clearly falls in the _marketing_ category and might be seen as an annoyance. Don't you agree?

**Comment by DeepDiver1975** [comment]
Okay - let's say I don't have the calendar app installed.
There is a new calendar release published.

We display on the left menu an entry 'New apps (1)' and when the user clicks on it all new apps (in this case calendar) is shown. 

A proper definition of 'new app' has to be found - maybe all new since last of the app. or simply any thing which is younger then 3 days.

**Comment by DeepDiver1975** [comment]
I dont consider this a marketing topic. This is not about advertising a release or what so ever.

**Comment by felixheidecke** [comment]
I guess this needs to be some kind of "message" since you should have the option to "mark as read". Otherwise, this counter would always be present and defeat its purpose of showing only things I haven't seen.
