### ISSUE TITLE
Add button to invalidate cache/force fetch data from marketplace

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/market#167]
The json data as queried from the marketplace is cached for 24hrs.

We shall give the admin the opportunity to force refresh.

Code location where data is written to the cache: https://github.com/owncloud/market/blob/master/lib/MarketService.php#L517

**Comment by patrickjahns** [comment]
I will provide a route that can be called from the frontend

**Comment by DeepDiver1975** [comment]
... and also an occ command

**Comment by felixheidecke** [comment]
This should also "refresh" on loading the app!

**Comment by DeepDiver1975** [comment]
> This should also "refresh" on loading the market app!

this will put to much load to the marketplace
