### ISSUE TITLE
Getting an app does not immediatly show it

### ISSUE THREAD

**Issue by mmattel** [owncloud/market#170]
Just upgraded to 10.0.3.3
Downloaded two apps (Gallery and Audio Player) via the market app.
After successfully installing by owncloud, it did not show up immediately.
I needed to switch to another page like settings to show up in
![image](https://user-images.githubusercontent.com/3321281/30587481-93b2e0c4-9d33-11e7-9e1f-6b48f75553ed.png)
This should be fixed to show up immediate after successful installing

**Comment by felixheidecke** [comment]
Unfortunately, this Element is not related to core and not to any app. New apps will only appear after a hard reload (F5). It's a core issue.

**Comment by DeepDiver1975** [comment]
Please try to call 
```js
OC.Settings.Apps.rebuildNavigation();
```

see https://github.com/owncloud/core/blob/f532f8701d4882f9225af9ab7a2dcb207883175e/settings/js/admin-apps.js#L227
