### ISSUE TITLE
Test app install behaviours on scaleouts

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/market#180]
set up test scenarios for clustered setups. What happens if
- a user installs an app via market app?
- a user installs an update via market app?
- a user installs an app via commandline?
- a user installs an update via commandline?

please extend test scenarios and list results here. This might affect https://github.com/owncloud/market/issues/179

As this affects the customer sync on marketplace it is critical and should be handled with higher priority.

**Comment by DeepDiver1975** [comment]
the result will be the same on all requested scenarios:
the app will be installed/updated on ONE node - via the web ui the node will be random. via the command line (occ) it will be the server on which the command is executed.

**Comment by hurradieweltgehtunter** [comment]
This is @patrickjahns task. Please do not close his issues.

**Comment by patrickjahns** [comment]
### Scenario: 
docker-setup with 2 owncloud containers (called A/B )/ 1 db container/ traefik reverse proxy

### Result:
> 1)  a user installs an app via market app?

It would be installed on the instance (A) where the command arrived. Reloading on the market app route would lead to:
- showing "Uninstall" if the request arrives at instance A
- show "install" when request arrives at instance B

> 2) a user installs an update via market app?
Instance A: version1 / instance B version2 
- when the request arrives at instance A - market app would show "update button" 
- when the request arrives at instance B - market app does show "uninstall" button

This can cause more issues: 
when the app is executed on A - it would trigger the old code
when the app is executed on B - it would use the new code

> 3) a user installs an app via commandline?
- it will only be installed on the instance where the command is run (instance A)

**result**
Instance A has it installed
Instance B does not have it installed

> 4) a user installs an update via commandline?
- it will only update the app on instances where command is run (Instance A)

**result**
Instance A has never version
Instance B has old version

### Additional findings
For 3) & 4) it is possible to run the command on the other Instance (B) and have a normal setup again. 

But this should only be done when owncloud is in maintenance mode
