### ISSUE TITLE
Set a link to the videos instead of plain text in the apps description

### ISSUE THREAD

**Issue by davitol** [owncloud/market#182]
![screen shot 2017-10-27 at 08 51 01](https://user-images.githubusercontent.com/10596560/32091647-5c1b7b28-baf5-11e7-9eba-87c3a2233c99.png)

**Comment by DeepDiver1975** [comment]
please test with master of market app - markdown support was recently added and the links shall properly be rendered.

furthermore I'd suggest to use animated pngs in screenshots.

**Comment by davitol** [comment]
@DeepDiver1975 as you said it works in master for market

![screen shot 2017-10-27 at 09 49 41](https://user-images.githubusercontent.com/10596560/32093547-edbba286-bafc-11e7-8511-b2ef430b08af.png)
![screen shot 2017-10-27 at 09 49 52](https://user-images.githubusercontent.com/10596560/32093551-f0d212f2-bafc-11e7-9713-aae7fb621e4c.png)

Let's close this ticket and open a separate one for animated pngs in screenshots if we want it.
