### ISSUE TITLE
successful Market Update does nothing

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/market#196]
![image](https://user-images.githubusercontent.com/16665512/32892308-14bfd1fc-cad6-11e7-8f4f-624c4fab3940.png)
After successfully updating the market app it still shows the update option. Looking into the installed app overview it still shows the old version
![image](https://user-images.githubusercontent.com/16665512/32892383-5a76ef50-cad6-11e7-8be8-2331ea312151.png)

There's no error displayed and the update request (POST /owncloud/index.php/apps/market/apps/market/update) returns status 200:
```message: "App market updated successfully"```

Am I doing sth wrong or is it buggy?

**Comment by DeepDiver1975** [comment]
same as this: https://central.owncloud.org/t/market-update-from-version-0-2-2-to-version-0-2-3-not-successful/10425/2
or this: https://github.com/owncloud/core/issues/29577

**Comment by hurradieweltgehtunter** [comment]
Thx. Changing the write permissions did the trick.
Updater should not show "Updated successful" though.

**Comment by DeepDiver1975** [comment]
> Updater should not show "Updated successful" though.

yes - but this is fixed in 0.2.3 - what can you do .... 😉

**Comment by hurradieweltgehtunter** [comment]
ah oh :D ok i see
thx
