### ISSUE TITLE
Which should be the version shown when running occ command with -V option

### ISSUE THREAD

**Issue by davitol** [owncloud/market#198]
Running the following command:

```
sudo -u www-data ./occ market:install --help
```
 it says: -V, --version         Display this application version

but running:
```
sudo -u www-data ./occ market:install -V
```

returns
ownCloud 10.0.3

instead of apps version.

**Comment by DeepDiver1975** [comment]
-V is a global option unrelated to an individual command and always returns the server version. As designed by the 3rd party lib symfony console
