### ISSUE TITLE
Problem load page market

### ISSUE THREAD

**Issue by d1mf** [owncloud/market#199]
I see  problem load page market 
http://prntscr.com/hiies9
Centos7, Nginx+php-fpm. database mariadb. Owncloud latest version. Php 7.1
Ty

{"reqId":"JInwPbqAVZDOTtdRqUYF","level":3,"time":"2017-12-03T16:40:46+02:00","remoteAddr":"77.123.55.120","user":"admin","app":"PHP","method":"GET","url":"\/apps\/market\/bundles","message":"array_map(): Argument #2 should be an array at \/var\/www\/html\/owncloud\/apps\/market\/lib\/Controller\/MarketController.php#83"}
{"reqId":"7kS2nCQxg781NfujYjTX","level":3,"time":"2017-12-03T16:40:48+02:00","remoteAddr":"77.123.55.120","user":"admin","app":"PHP","method":"GET","url":"\/apps\/market\/bundles","message":"array_map(): Argument #2 should be an array at \/var\/www\/html\/owncloud\/apps\/market\/lib\/Controller\/MarketController.php#83"}
{"reqId":"bXBjWijVSd5ics3oMjle","level":3,"time":"2017-12-03T16:40:49+02:00","remoteAddr":"77.123.55.120","user":"admin","app":"PHP","method":"GET","url":"\/apps\/market\/bundles","message":"array_map(): Argument #2 should be an array at \/var\/www\/html\/owncloud\/apps\/market\/lib\/Controller\/MarketController.php#83"}
{"reqId":"x20lLBrqfmsVlymOfkXx","level":3,"time":"2017-12-03T16:40:51+02:00","remoteAddr":"77.123.55.120","user":"admin","app":"PHP","method":"GET","url":"\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/var\/www\/html\/owncloud\/apps\/market\/lib\/Controller\/MarketController.php#227"}

**Comment by DeepDiver1975** [comment]
I assume this was a temporary system hickup - please test again. THX

**Comment by davitol** [comment]
If it is not longer reproducible, let's close the ticket. @d1mf Feel free to reopen it if is still reproducible
