### ISSUE TITLE
Apps don't show up in Market app

### ISSUE THREAD

**Issue by Jolopu** [owncloud/market#228]
OC Version: 10.0.4
Market app: 0.2.3

Issue: Apps don't show up in Market app

Chrome console error:

vue.runtime.esm.js?a427:559 TypeError: Cannot read property 'length' of null
    at VueComponent.render (List.vue?0898:29)
    at VueComponent.Vue._render (vue.runtime.esm.js?a427:4191)
    at VueComponent.updateComponent (vue.runtime.esm.js?a427:2570)
    at Watcher.get (vue.runtime.esm.js?a427:2913)
    at Watcher.run (vue.runtime.esm.js?a427:2990)
    at flushSchedulerQueue (vue.runtime.esm.js?a427:2756)
    at Array.eval (vue.runtime.esm.js?a427:694)
    at nextTickHandler (vue.runtime.esm.js?a427:641)
    at <anonymous>

![oc-market-app](https://user-images.githubusercontent.com/34797349/34382010-1c6f69bc-eb47-11e7-96bc-68dd48783940.png)

**Comment by patrickjahns** [comment]
Can you provide additional information? Is there anything shown in the owncloud.log ?

**Comment by Jolopu** [comment]
Here the latest owncloud.log:

{"reqId":"Wj6TVyUR4EsAAEyHSNYAAAAH","level":3,"time":"2017-12-23T17:33:12+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"Wj6ThSUR4EsAAGFT9vUAAAAB","level":3,"time":"2017-12-23T17:33:58+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/bundles","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#83"}
{"reqId":"Wj6TjCUR4EsAAEx0e1gAAAAF","level":3,"time":"2017-12-23T17:34:04+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"Wj-lAiUR4EsAABmnwc8AAAAA","level":2,"time":"2017-12-24T17:33:55+00:00","remoteAddr":"209.58.185.46","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/1B50A242-9C08-42A7-872D-7F584D3D45F7.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/1B50A242-9C08-42A7-872D-7F584D3D45F7.ics\" : {$message}"}
{"reqId":"Wj-lAiUR4EsAABmnwc8AAAAA","level":2,"time":"2017-12-24T17:33:55+00:00","remoteAddr":"209.58.185.46","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/1B50A242-9C08-42A7-872D-7F584D3D45F7.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/1B50A242-9C08-42A7-872D-7F584D3D45F7.ics\" : {$message}"}
{"reqId":"Wj-lCiUR4EsAAFKSm7YAAAAF","level":2,"time":"2017-12-24T17:34:03+00:00","remoteAddr":"209.58.185.46","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/F280250D-9083-4762-83F6-AB14FE5E6EA0.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/F280250D-9083-4762-83F6-AB14FE5E6EA0.ics\" : {$message}"}
{"reqId":"Wj-lCiUR4EsAAFKSm7YAAAAF","level":2,"time":"2017-12-24T17:34:03+00:00","remoteAddr":"209.58.185.46","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/F280250D-9083-4762-83F6-AB14FE5E6EA0.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/F280250D-9083-4762-83F6-AB14FE5E6EA0.ics\" : {$message}"}
{"reqId":"WkJlvSUR4EsAAD7SmREAAAAE","level":2,"time":"2017-12-26T15:07:41+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Neuer%20Ordner","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Neuer Ordner\" : {$message}"}
{"reqId":"WkJlzSUR4EsAAD7SmRIAAAAE","level":2,"time":"2017-12-26T15:07:57+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Videos\/Bassilyo%20-%20Lord%20Patawad.mp3","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Videos\/Bassilyo - Lord Patawad.mp3\" : {$message}"}
{"reqId":"WkJlzSUR4EsAAG@SvDkAAAAF","level":2,"time":"2017-12-26T15:07:58+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Videos\/Linkin%20Park%20-%20Ill%20Be%20Gone.mp3","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Videos\/Linkin Park - Ill Be Gone.mp3\" : {$message}"}
{"reqId":"WkJlzSUR4EsAAG-X8cwAAAAB","level":2,"time":"2017-12-26T15:07:58+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Videos\/Martin%20Garrix%20&%20Dua%20Lipa%20-%20Scared%20To%20Be%20Lonely.mp3","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Videos\/Martin Garrix & Dua Lipa - Scared To Be Lonely.mp3\" : {$message}"}
{"reqId":"WkJlzSUR4EsAAD7SmRMAAAAE","level":2,"time":"2017-12-26T15:07:58+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Videos\/SAIL%20-%20AWOLNATION.mp3","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Videos\/SAIL - AWOLNATION.mp3\" : {$message}"}
{"reqId":"WkJlziUR4EsAAAZ6dSsAAAAA","level":2,"time":"2017-12-26T15:07:59+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Videos\/Sex%20Whales%20-%20One%20Day.mp3","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Videos\/Sex Whales - One Day.mp3\" : {$message}"}
{"reqId":"WkJq2SUR4EsAAAZ6dVUAAAAA","level":2,"time":"2017-12-26T15:29:29+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Fotos\/20170918_120035.jpg","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Fotos\/20170918_120035.jpg\" : {$message}"}
{"reqId":"WkNYiCUR4EsAAHq6V64AAAAB","level":3,"time":"2017-12-27T08:23:36+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"WkNZRSUR4EsAAG-A1OsAAAAC","level":3,"time":"2017-12-27T08:26:45+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"WkNZziUR4EsAAAKVHLwAAAAA","level":3,"time":"2017-12-27T08:29:02+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"WkNcKCUR4EsAAG-A1RUAAAAC","level":2,"time":"2017-12-27T08:39:05+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/EF81294F-FBBE-4034-9CF9-95BCD4C8C6B8.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/EF81294F-FBBE-4034-9CF9-95BCD4C8C6B8.ics\" : {$message}"}
{"reqId":"WkNd-CUR4EsAAH39yeMAAAAD","level":3,"time":"2017-12-27T08:46:53+00:00","remoteAddr":"185.230.127.30","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"WkNgXiUR4EsAAG-A1VAAAAAC","level":2,"time":"2017-12-27T08:57:02+00:00","remoteAddr":"91.47.205.150","user":"gaby","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/calendars\/gaby\/tt_shared_by_Manfred\/0fd34913-b0f9-4674-99be-7f495e5e0183.ics","message":"Could not get node for path: \"calendars\/gaby\/tt_shared_by_Manfred\/0fd34913-b0f9-4674-99be-7f495e5e0183.ics\" : {$message}"}
{"reqId":"WkOVvCUR4EsAAH39y3sAAAAD","level":3,"time":"2017-12-27T12:44:44+00:00","remoteAddr":"194.88.105.17","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"WkOZKCUR4EsAAFB0PsMAAAAE","level":3,"time":"2017-12-27T12:59:21+00:00","remoteAddr":"194.88.105.17","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"WkQ7oCUR4EsAADLWdwoAAAAC","level":2,"time":"2017-12-28T00:32:32+00:00","remoteAddr":"185.230.127.3","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Dokumente\/Versichertenkarte%20Teroerde.pdf","message":"Could not get node for path: \"files\/Manfred\/Dokumente\/Versichertenkarte Teroerde.pdf\" : {$message}"}
{"reqId":"Wkca5iUR4EsAAAaM0zMAAAAB","level":2,"time":"2017-12-30T04:49:43+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/FE456C36-AF1B-4BCE-84B8-D3B13CDC67A4.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/FE456C36-AF1B-4BCE-84B8-D3B13CDC67A4.ics\" : {$message}"}
{"reqId":"Wkca5iUR4EsAAAaM0zMAAAAB","level":2,"time":"2017-12-30T04:49:43+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/calendars\/Manfred\/Manfred\/FE456C36-AF1B-4BCE-84B8-D3B13CDC67A4.ics","message":"Could not get node for path: \"calendars\/Manfred\/Manfred\/FE456C36-AF1B-4BCE-84B8-D3B13CDC67A4.ics\" : {$message}"}
{"reqId":"Wkit0iUR4EsAAFMj14wAAAAA","level":2,"time":"2017-12-31T09:28:50+00:00","remoteAddr":"91.47.207.225","user":"gaby","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/files\/gaby\/Website\/forest-1835811_1280.jpg","message":"Could not get node for path: \"files\/gaby\/Website\/forest-1835811_1280.jpg\" : {$message}"}
{"reqId":"WkjO@iUR4EsAABlYhDsAAAAB","level":2,"time":"2017-12-31T11:50:19+00:00","remoteAddr":"185.230.127.27","user":"Manfred","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/files\/Manfred\/Website\/die-etwas-andere-perspektive.mp3","message":"Could not get node for path: \"files\/Manfred\/Website\/die-etwas-andere-perspektive.mp3\" : {$message}"}
{"reqId":"WkjPBCUR4EsAABlYhDwAAAAB","level":2,"time":"2017-12-31T11:50:28+00:00","remoteAddr":"185.230.127.27","user":"Manfred","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/files\/Manfred\/Website\/der-ausweg-fuehrt-nach-oben.mp3","message":"Could not get node for path: \"files\/Manfred\/Website\/der-ausweg-fuehrt-nach-oben.mp3\" : {$message}"}
{"reqId":"Wkmo2CUR4EsAAB7mlI0AAAAA","level":3,"time":"2018-01-01T03:19:52+00:00","remoteAddr":"185.230.127.29","user":"Manfred","app":"PHP","method":"GET","url":"\/index.php\/apps\/market\/apps","message":"array_map(): Argument #2 should be an array at \/home\/www\/cloud.geistigewelt.tv\/apps\/market\/lib\/Controller\/MarketController.php#227"}
{"reqId":"Wkno2SUR4EsAABXXVuQAAAAC","level":2,"time":"2018-01-01T07:52:57+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Dokumente\/Rudolf_Meier_ID.jpg","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Dokumente\/Rudolf_Meier_ID.jpg\" : {$message}"}
{"reqId":"WknrqSUR4EsAAB7mlbMAAAAA","level":2,"time":"2018-01-01T08:04:57+00:00","remoteAddr":"210.4.108.202","user":"Manfred","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/files\/Manfred\/Manfred\/Dokumente\/GCrush.jpg","message":"Could not get node for path: \"files\/Manfred\/Manfred\/Dokumente\/GCrush.jpg\" : {$message}"}

**Comment by davitol** [comment]
It seems everything works fine in oC 10.1 and latest market app version. If it is still reproducible after the upgrade, feel free to reopen the ticket. Thanks for reporting
