### ISSUE TITLE
update notification link does not use correct hostname

### ISSUE THREAD

**Issue by tomneedham** [owncloud/market#236]
<img width="426" alt="screen shot 2018-01-12 at 12 48 21" src="https://user-images.githubusercontent.com/660805/34875865-f0e7729c-f796-11e7-960d-b611e37ac248.png">

points to http://localhost/index.php/apps/market/#/app/market instead of customer.staging.owncloud.com/.....

**Comment by tomneedham** [comment]
10.0.3 core && 0.2.2 market

**Comment by DeepDiver1975** [comment]
Config is not set properly. Overwrite URL something is the Parameter
