### ISSUE TITLE
app names too long

### ISSUE THREAD

**Issue by voroyam** [owncloud/market#238]
Some of the apps start with external storage but the rest of the app name, what differentiates them, isn't shown. can this be adjusted?

![storage](https://user-images.githubusercontent.com/24212810/34995787-d58f1e70-fad7-11e7-9628-d9bff72038e3.png)

also why is the FTP app not in storage? O_O

**Comment by DeepDiver1975** [comment]
> also why is the FTP app not in storage? O_O

you can find it in external-plugins - the next version will move it to storage

**Comment by DeepDiver1975** [comment]
> Some of the apps start with external storage but the rest of the app name, what differentiates them, isn't shown. can this be adjusted?

@felixheidecke and idea on how to fix this? THX

**Comment by hurradieweltgehtunter** [comment]
The title should not include the category

**Comment by felixheidecke** [comment]
I'll go ahead and move the start-rating to another position. This also helps on smaller viewports.

**Comment by hurradieweltgehtunter** [comment]
testcomment. please ignore

**Comment by voroyam** [comment]
@felixheidecke can you give me an update on this?
