### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by voroyam** [owncloud/market#255]
Can't get the Enterprise Trial working

Steps to reproduce:

1. start a new docker container ( own docker not owncloud docker with docker compose )
2. get oc 10.0.4
3. generate a new email address for market
4. go to https://marketplace.owncloud.com
5. register for a new trial and get API Key
6. Go to owncloud, click on the blue Start Enterprise Trial Button
7. Paste the Enterprise key and Click on save
8. Click on Close
9. I see the Enterprise Bundle Apps but Cant download them
10. Refresh the page and get this:

![market](https://user-images.githubusercontent.com/24212810/36256699-40666030-1254-11e8-9ba5-2e0e6c5138c2.png)
![market-fehler](https://user-images.githubusercontent.com/24212810/36256701-43e113ae-1254-11e8-94d8-f5601e32d259.png)

I tried to edit the key, delete it and save it, then pasting the key again, but it does not solve the problem, "invalid API key" is shown again.

Edit:

Tried the official ownCloud docker container.

Now I don't get the Invalid API Key message, I just can't download the enterprise Apps.

![grey](https://user-images.githubusercontent.com/24212810/36258008-7393c664-1259-11e8-9558-75d89a9de2a9.png)

Market app is Version 0.2.3

Video of the process:

https://cloud.owncloud.com/index.php/s/aoF5CkMEUpoC5vW
PW: 
111

**Comment by hurradieweltgehtunter** [comment]
@felixheidecke @IljaN

**Comment by IljaN** [comment]
Fixed
