### ISSUE TITLE
Past enabled apps still generate update notifications even when uninstalled

### ISSUE THREAD

**Issue by tomneedham** [owncloud/market#270]
Please consider this case then, as experienced by @dercorn :

 - You install an app
 - You enable and app
 - It utilises appconfig keys
 - You disable the app
 - An app update is published
 - Marketplace notifcation created for the admin
 - You uninstall the app (folder actually removed)
 - You dismiss the update notification

Now - everytime the marketplace update cron runs you get a notification for an update to an app that you have disabled AND uninstalled. Every time. Even if you dismiss. This is not acceptable IMO - we need another way to stop this.

Ok so I understand that the market service needs to know about updates. Perhaps then the notifications should only be generated for apps that you have enabled - but in the background the app knows about all updates that are possible...

cc @DeepDiver1975

**Comment by VicDeo** [comment]
mmm... 
`getInstalledApps` returns **enabled** apps
`getAllApps` returns **enabled, disabled and deleted** apps
and  there is no method that returns just **enabled and disabled** apps

**Comment by VicDeo** [comment]
Basically  `OC_App::getAllApps` iterates through all approots and returns all subdirs that have `appinfo.xml` inside
it also has this nice todo  https://github.com/owncloud/core/blob/master/lib/private/legacy/app.php#L782
:)

**Comment by VicDeo** [comment]
oh. I overlooked "Every time. Even if you dismiss"

**Comment by VicDeo** [comment]
@tomneedham I tried the following steps with maket app at master branch:
1. Run cron.php
2. Got update notifications about theme-enterprise, calendar, WND
3. Uninstalled theme-enterprise - checked that code was deleted
4. Dismissed theme-enterprise notification
5. Set marketplace job frequency to 1 minute
6. Run cron.php - no notification about theme-enterprise
7. Dismissed calendar, WND
8. Run cron.php - no notification about calendar, WND,  theme-enterprise
9. Installed|enabled customgroups v0.3.5
10. Run cron.php - got update notification about Custom groups 0.3.6

May be I'm doing something wrong...

**Comment by VicDeo** [comment]
@dercorn could you specify what OC version should I retry these steps with?

**Comment by VicDeo** [comment]
Anyway https://github.com/owncloud/market/pull/285 should be the rescue
