### ISSUE TITLE
Notification URL setting

### ISSUE THREAD

**Issue by voroyam** [owncloud/market#315]
In the Appliance, the OC version is currently 10.0.4.

If I click on the notification bell, and then select a notification, the URL is http://localhost/something

But if I access the Appliance via the IP address, the URL should change to http://IP_Address/something

Because the URL does not change, I get redirected to a invalid site and can'f perform the update of the app.

Can someone tell me where this URL gets generated and what parameters one would have to change to fix this?

**Comment by PVince81** [comment]
@voroyam likely "overwrite.cli.url" in config.php and possibly some others of the "overwrite.*" options. should be in the docs

**Comment by voroyam** [comment]
@PVince81 I already tried to adjust this line in the config.php. Nothing changes after a reload / restart of the apache server.

**Comment by voroyam** [comment]
![grafik](https://user-images.githubusercontent.com/24212810/38561400-3897b224-3cd8-11e8-9170-28a3d5e44a08.png)

**Comment by PVince81** [comment]
why is it commented out?

**Comment by PVince81** [comment]
please try the other ones: "overwrite.host", etc. see documentation.

**Comment by voroyam** [comment]
Because I was trying some things

**Comment by PVince81** [comment]
by the way, restarting the server will not help because the notification is likely already created in oc_notifications with the old URL. You need to find a way to retrigger the notification to get a new entry

**Comment by voroyam** [comment]
Yeah, I don't know how to do this. I have looked in the database in the oc_notifications table but could not find the entry.

This table is just for the notification, but I looked in oc_properties, oc_preferences, oc_appconfig. Nothing.

Maybe @IljaN  has an idea

**Comment by PVince81** [comment]
@jvillafanez should know more as he worked on notifications lately

**Comment by jvillafanez** [comment]
What app is sending the notification?
Are you accessing ownCloud via localhost, or via ip address?

**Comment by voroyam** [comment]
Ip Address

user_ldap and template editor

![grafik](https://user-images.githubusercontent.com/24212810/38564324-35c3b460-3cdf-11e8-97bf-273ae9b11eb4.png)

**Comment by jvillafanez** [comment]
https://github.com/owncloud/market/blob/89ea65a5bc58dfbdfc67a142b27e1b7b7fc21097/lib/CheckUpdateBackgroundJob.php#L93

I guess that should be the piece generating the notification

**Comment by voroyam** [comment]
alright, now we just have to trigger an update process to this, right?

**Comment by voroyam** [comment]
I have found this function, that generates the URL:

OCP\IURLGenerator

**Comment by voroyam** [comment]
@jvillafanez @PVince81 @IljaN 

any update on this?

**Comment by jvillafanez** [comment]
If it's a configuration problem as it seems, I don't think we can do anything about it from a dev point of view. The notification is generated by a cron job which isn't served by the web server, so we can't know the server url and we have to rely on the overwrite.cli.url configuration option. If such option isn't properly configured there isn't anything we can do.

**Comment by DeepDiver1975** [comment]
> moved this to the appliance repository,

closing then
