### ISSUE TITLE
Maket 0.2.4 causes "Failed to perform request for notifications" and "File integrity errors"

### ISSUE THREAD

**Issue by careyer** [owncloud/market#326]
After installing market 0.2.4 on my RaspberryPi3 based Owncloud 10.0.4 it immediatly started to give me errors:

"Failed to perform request for notifications" on each and every loaded site
and 
various file integrity errors during the integrity check.

I had to revert to a backuped copy of my owncloud and data drive

**Comment by patrickjahns** [comment]
Please provide `owncloud.log` and further information that can help with analysing

**Comment by patrickjahns** [comment]
Closing as no further information has been provided
