### ISSUE TITLE
LDAP app is not updated from 0.10.0 to 0.11.0 using market webUI and oC 10.0.7

### ISSUE THREAD

**Issue by davitol** [owncloud/market#346]
![ldap](https://user-images.githubusercontent.com/10596560/39745333-3ab37da6-52a7-11e8-9fc8-38b408c5b84e.gif)

**Comment by IljaN** [comment]
@davitol Which marketplace app version?

**Comment by IljaN** [comment]
Reproduceable  with 10.0.7 (shipped and latest market app) but not with 10.0.8

**Comment by IljaN** [comment]
Issue is on market

**Comment by IljaN** [comment]
Deployment will be next week

**Comment by IljaN** [comment]
Marketplace deployed
