### ISSUE TITLE
Apps cannot be installed using UI button.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#35]
### Steps to reproduce

0. Having environment set up with certificate provided and vpn connected do:
1. Go to market app.
2. Choose an app available (for example, contacts one), click in more.
2. Try to install it (click in install button).

### Expected behaviour
Contacts is installed.

### Actual behaviour
It cannot be installed.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.7","versionstring":"10.0.0 RC1","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"EqhiFDfLNd9ZXs1g8U12","level":3,"time":"2017-04-21T06:57:41+00:00","remoteAddr":"127.0.0.1","user":"ser","app":"PHP","method":"POST","url":"\/tarball_20-04-17\/index.php\/apps\/market\/apps\/contacts\/install","message":"Undefined index: appdata at \/var\/www\/html\/tarball_20-04-17\/lib\/private\/Installer.php#336"}
```
### Client configuration

**Browser**
Firefox

**Logs**
```
```

**Comment by DeepDiver1975** [comment]
The error will not prevent installation

**Comment by SergioBertolinSG** [comment]
Fixed.
