### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/market#358]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.appendTo()`

- [x] /src/store.js

`.toggle()`

- [x] src/components/ApiForm.vue
- [x] src/components/Trial.vue

**Comment by PVince81** [comment]
please add reason for closing for future reference

**Comment by felixheidecke** [comment]
Works fine :-)
