### ISSUE TITLE
Adjust update process to work with market

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#39]
Here is how the core update must be work when running `occ upgrade`

1. Check for apps that have missing app code, store in a list
1. Check for apps that are present but are incompatible, store in same list
1. Check market connectivity. If no internet => fail with message "please install app manually with tarball, or disable app with occ app:disable"
1. For each app, try to retrieve and install from the market (but don't enable). If an app is missing, abort and display the message above.
1. When all went well, enable all apps (or only the "authenitcation" ones) <= to be discussed, maybe the update process takes care of that already

This should already properly cover both unbundling and future app upgrades.

- Missing app code check is in this PR: https://github.com/owncloud/core/pull/27047
- Code for fetching from market is here: https://github.com/owncloud/core/pull/27711

@VicDeo can you synergize the PRs to make them behave as per the steps above ?

cc @DeepDiver1975 @butonic as discussed

**Comment by VicDeo** [comment]
@PVince81 withing upgrade process only `authenitcation` apps are loaded 

What should happen in case `market` app is disabled?

**Comment by PVince81** [comment]
Then let's only load "authentication" apps as well after the above sequence.

I think people who purposefully disable the market app are those with offline instances. It's pointless to have the GUI present when it cannot connect to the market. In this case we don't attempt to connect (I think the event won't trigger anything) and directly show an error message about updating manually or disabling the apps.

**Comment by PVince81** [comment]
- [ ] show error directly if "market" app is disabled (same as for no connectivity)

**Comment by PVince81** [comment]
Now thinking, should we actually attempt to update ALL apps instead of just the missing/incompatible ones during occ upgrade ?

However for compatible apps, if no update is found or no market entry or market not reachable, we just skip it instead of aborting.

Thoughts ?

**Comment by VicDeo** [comment]
@PVince81 ok, so we iterate though all apps sorting them and then
<table>
<tr>
<th>has update</th>
<th>compatible</th>
<th>incompatible</th>
<th>missing</th>
<th>disabled</th>
</tr>
<tr>
<td>Yes</td>
<td>update</td>
<td>update</td>
<td>update</td>
<td>update</td>
</tr>
<tr>
<td>No</td>
<td>pass</td>
<td>fail</td>
<td>fail</td>
<td>pass</td>
</tr>
</table>

**Comment by PVince81** [comment]
don't update disabled apps but "skip", just leave them lying around... they might be disabled because broken. the admin can always update them manually in the market app later.

**Comment by PVince81** [comment]
This is done
