### ISSUE TITLE
hookup into update procedure to trigger app updates after core update

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/market#4]

**Comment by PVince81** [comment]
@VicDeo @DeepDiver1975 isn't this critical for proper functioning with the market ?

While we might not have app updates in 10.0, there will likely be app updates to be triggered when updating the platform to 10.0.1.

Please evaluate and schedule.

**Comment by PVince81** [comment]
AFAIK we don't need this and updates already work now in 10.0.2 ?

**Comment by DeepDiver1975** [comment]
we have that in place already -> close
