### ISSUE TITLE
Enterprise trial does not work most of the time

### ISSUE THREAD

**Issue by va1entin** [owncloud/market#410]
It's currently a big hassle to start an enterprise trial because it just does not work most of the time. I'm using two separate test systems running UCS 4.3-1 with Owncloud 10.0.9 and up to date market app. I supply the API key and start the enterprise trial. Afterwards one of the following happens in about 9/10 tries:

- license key app can be installed, all other enterprise apps say "your license key is not valid"
- no enterprise apps can be installed ("view in marketplace" is the only option)

Sometimes (1/10 times) it just works and I can just install the enterprise apps. The volatility of this problem makes it hard to debug for me. I'll gladly supply any logs you might need.

I've tried the following multiple times:
- reset to snapshot after owncloud installation
- regenerate API key
- use owncloud 10.0.8 and old market app version
- clear cache in market app

**Comment by PVince81** [comment]
@voroyam I seem to remember that you also observed some random issue in https://github.com/owncloud/market/issues/260 with the appliance at some point, something about caching ?

@va1entin did you reset the appliance from scratch between your retries ?

**Comment by va1entin** [comment]
@PVince81 I reset it to a snapshot before Owncloud was installed and always installed it from scratch. Btw. clearing the market app cache doesn't help either, I've added that to the initial issue description.

**Comment by IljaN** [comment]
@va1entin Are you using a fresh marketplace account every time? Once a trial is started with a certain api-key it can't be restarted with the same account.

**Comment by IljaN** [comment]
@PVince81 This issue might be resolved with next deployment because we fixed a few bugs regarding trial. But I suspect that @va1entin might have tried to start multiple trials with the same account. Maybe we need to give a more clear error-message.

**Comment by va1entin** [comment]
@IljaN Sorry for the late answer! I was using the same marketplace account most of the time, because the web interface let me freely regenerate new API keys, which is why I thought the trial was tied to the key and not to the account behind it. Since that doesn't seem to be case, it might be more intuitive to just use the marketplace account itself for the trial registration in Owncloud in the first place? Surely there's some technical reason why that's not the workflow so far, though.
Still, I'm rather certain, that I had this problem with brand new accounts as well.

I'll gladly try again after the next deployment, do you mind posting a comment when it happened or when it's due?

**Comment by PVince81** [comment]
@IljaN marketplace was deployed, close ?
