### ISSUE TITLE
[For 10.1] Market 0.3.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#417]
### Reason
- Differenciate between minor and major upgrades: https://github.com/owncloud/market/issues/387
- Fix bug with "--all" switch: https://github.com/owncloud/market/pull/388
- Dependency updates: https://github.com/owncloud/market/pull/407

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "0.3.0 Testplan" https://github.com/owncloud/market/issues/419

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/market/pull/418
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/market/pull/418
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist`
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Github release
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/market/pull/433

**Comment by PVince81** [comment]
@davitol FYI

**Comment by PVince81** [comment]
market 0.3.0 RC1: https://cloud.owncloud.com/index.php/s/2XJlu8EsggAdQHk

**Comment by PVince81** [comment]
market 0.3.0 RC2: https://cloud.owncloud.com/index.php/s/MBBSXCzm89AJTFN

@davitol @VicDeo FYI  ^

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready with some known issues that are not regressions:

https://github.com/owncloud/market/issues/423

https://github.com/owncloud/market/issues/426

**Comment by PVince81** [comment]
it turns out that CI showed green but did not run actual tests when we worked on the various PRs, and now we see failures for the upgrade commands: https://github.com/owncloud/market/issues/434.

I've pulled market-0.3.0 from marketplace to avoid people upgrading to this version.

We'll publish another release with a fix.

**Comment by PVince81** [comment]
unit tests pass locally for me on release-0.3.0, so it's likely that the release is ok.
they fail on master only
