### ISSUE TITLE
Improve install button behaviour

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#42]
**Steps**

0. Having market app well configured, access to an app description
1. Click in install button.

**Current behaviour:**

Nothing happens in the UI. It doesn't tell if the installation is finished, ok or what has happened
if you click the install button again there is an exception in the logs saying that the app is already installed but nothing in the ui.

**Expected behaviour**

The UI tells you that the app has been installed correctly and the install button is no longer available to be pressed again.

Maybe change the install button for an uninstall button.

**Comment by tboerger** [comment]
This will be solved via https://github.com/owncloud/market/pull/37

**Comment by tboerger** [comment]
Fixed

**Comment by davitol** [comment]
Tested in oCRC4 and the issue keeps happening

> Click in install button.
> 
> Current behaviour:
> 
> Nothing happens in the UI. It doesn't tell if the installation is finished, ok or what has happened

**Comment by tboerger** [comment]
But this is fixed on master. Currently it's switching to `Installing...` and with another pending PR by @felixheidecke it's also showing a spinner.

**Comment by davitol** [comment]
Let's keep this ticket opened until @felixheidecke will finish the spinner PR

**Comment by felixheidecke** [comment]
Fixed with https://github.com/owncloud/market/pull/53

**Comment by felixheidecke** [comment]
Fixed with https://github.com/owncloud/market/pull/64
