### ISSUE TITLE
Auto-enable after install

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#43]
I suggest that `market::install` and the UI automatically enable the app, it's much more intuitive.

In the event that an admin wants to install without enabling, if that's really needed, we could add an option `market::install someapp --no-enable`

@DeepDiver1975 @SergioBertolinSG @VicDeo thoughts ?

**Comment by PVince81** [comment]
Tagging as usability bug.

I only used the market UI and command twice so far and was confused again thinking it's broken because the contacts app didn't appear and I had to go to the "Apps" section in the settings to enable it.

**Comment by PVince81** [comment]
I'd like to have this for 10.0 if possible

**Comment by felixheidecke** [comment]
FE code isn't concerned with this

**Comment by PVince81** [comment]
thanks, incoming PR ? apparently it's not directly on master

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/market/pull/46 - in here together with uninstall
