### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/market#434]
https://drone.owncloud.com/owncloud/market/31/31
```
php -d zend.enable_gc=0  "/var/www/owncloud/apps/market/../../lib/composer/bin/phpunit" --configuration ./phpunit.xml --testsuite unit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.23-3+ubuntu16.04.1+deb.sury.org+1
Configuration: /var/www/owncloud/apps/market/phpunit.xml
Error:         No code coverage driver is available

..........................F......F...........................     61 / 61 (100%)

Time: 486 ms, Memory: 16.00MB

There were 2 failures:

1) OCA\Market\Tests\Unit\Command\UpgradeAppTest::testUpdateNoNewVersion
Failed asserting that 'foo: Installing new version  ...
foo: OCA\Market\MarketService::updateApp('foo', null) was not expected to be called.
' contains "foo: No update available".

/var/www/owncloud/apps/market/tests/unit/Command/UpgradeAppTest.php:91

2) OCA\Market\Tests\Unit\Command\UpgradeAppTest::testInstallRefusesMajorUpgrade
Failed asserting that 'bla: Installing new version  ...
bla: App updated.
' contains "update to 2.0.0 requires --major option".

/var/www/owncloud/apps/market/tests/unit/Command/UpgradeAppTest.php:228

FAILURES!
Tests: 61, Assertions: 119, Failures: 2.
Makefile:139: recipe for target 'test-php-unit' failed
make: *** [test-php-unit] Error 1 
```

**Comment by phil-davis** [comment]
Somehow unit tests never got run in CI in the process of merging #424 into ``release-0.3.0`` branch 21 days ago.

Since then, CI has been moved to drone.

Somehow when merging ``release-0.3.0`` branch to ``master`` yesterday in PR #433 "the system" did not run drone. Something because of ``release-0.3.0`` branch having been created before the move of CI to drone, and merged after???

I noticed the problem because I added market app to the drone nightly jobs yesterday and checked it this morning.

The unit test fails look like there will really be a problem @PVince81 @VicDeo

**Comment by PVince81** [comment]
this is the breaking commit: 439a49af0f3a7de73ed597784997cb19015a1c18 from https://github.com/owncloud/market/pull/424

The weird part is that the PR was targetting the release-0.3.0.

So maybe the PR only started to break the tests after merging ??

**Comment by PVince81** [comment]
my local release-0.3.0  branch was still on RC1. now with RC2 the unit tests fail as well.
ok, back to the world of logic.

**Comment by PVince81** [comment]
and indeed CI showed green but did not run tests back then:
![image](https://user-images.githubusercontent.com/277525/50327693-68e4d480-04f0-11e9-9806-312f6c1945e2.png)

**Comment by PVince81** [comment]
Case closed https://github.com/owncloud/market/pull/437
