### ISSUE TITLE
Unable to update from 0.2.5 to 0.3.0

### ISSUE THREAD

**Issue by wolkenschieber** [owncloud/market#439]
## Bug report

I'm unable to update the Market App from 0.2.5 to 0.3.0. The process fails due to failed code check.

### Steps to reproduce

1. Open Market App
1. Install Market Update

### Code-Check

Verifying the app using `occ` produces following output:
```
$ ./occ app:check-code market
ownCloud is in maintenance mode - no app have been loaded

Analysing /var/www/owncloud/apps/market/lib/Notifier.php
 1 errors
    line  107: OC_App - Static method of private class must not be called
Analysing /var/www/owncloud/apps/market/lib/MarketService.php
 2 errors
    line  281: OC_App - Static method of private class must not be called
    line  601: OC_App - Static method of private class must not be called
Analysing /var/www/owncloud/apps/market/lib/Controller/LocalAppsController.php
 1 errors
    line   46: OC_App - Static method of private class must not be called
App is not compliant
```

**Comment by DeepDiver1975** [comment]
> ./occ app:check-code market

this command is a tool for developers to support them during their development work. This is unrelated to any installation issues.

What error do you get on updating the market app? THX

**Comment by DeepDiver1975** [comment]
Please disable the code checker - we already dropped it on the master branch.

Set this setting in config.php to false https://github.com/owncloud/core/blob/873736bf64ec79b76bc80a77644765290bb82553/config/config.sample.php#L563

**Comment by DeepDiver1975** [comment]
We are removing the code checker in 10.1 -> https://github.com/owncloud/core/pull/34049

**Comment by wolkenschieber** [comment]
Disabling the code checker allowed me to update the app. Thanks!
