### ISSUE TITLE
Usability improvement: add link to marketplace in warning about missing API key

### ISSUE THREAD

**Issue by dercorn** [owncloud/market#463]
This should be a quick and easy one:

when the error message about a missing API key appears, please add a note on where to get it.
This will save a lot of people in the company the time and effort to write an email explaining the process over and over again every single time.

Example:
"Marketplace API key missing. Get one at https://marketplace.owncloud.com/"

**Comment by PVince81** [comment]
@karakayasemi something for you later on ?

**Comment by karakayasemi** [comment]
We can schedule it to me for next week.
