### ISSUE TITLE
Adding empty API Key results in broken app

### ISSUE THREAD

**Issue by cortho** [owncloud/market#480]
When I click Settings -> Edit API Key, delete the Key and save it, the market app wouldn't display any apps any more.

Expected behaviour would be, that there is no API Key and I can see the app list, such as in a fresh installation.

See the Screenshot - at a first glance it looks like "" (empty string) is saved as my new API key. 
I would have expected that the prior key would be removed.

![marketplace-empty-apikey](https://user-images.githubusercontent.com/28009362/58885756-09b3fe80-86e3-11e9-81eb-d59d14010b7d.png)

Edit: Replaced Screenshot

**Comment by mraumala-roku** [comment]
Just upgraded ownCloud to 10.9.0.3 which broke the Market app that had worked just fine without the API Key.

I was getting these 403 Forbidden responses and tracked it to down to apps/market/lib/HttpService.php...
```
    public function getApiKey() {
        $configFileApiKey = $this->config->getSystemValue('marketplace.key', null);
        if ($configFileApiKey) {
            return $configFileApiKey;
        }
        return $this->config->getAppValue('market', 'key', null);
    }

    private function httpGet($path, $options, $apiKey) {
        if ($apiKey !== null) {
            $options = \array_merge(
                [
                    'headers' => ['Authorization' => "apikey: $apiKey"]
                ],
                $options
            );
        }
```
My first instinct to correct this in the UI with the **Settings -> Edit API Key** and save an empty key. Like Thomas above I expected this to remove the key in the absence of any other UI to delete an existing key.

In the end, I had to delete the market.key from the database...
```
MariaDB [owncloud]> SELECT * FROM oc_appconfig WHERE appid="market" AND configkey="key" \G
*************************** 1. row ***************************
      appid: market
  configkey: key
configvalue: 
1 row in set (0.000 sec)

MariaDB [owncloud]> DELETE FROM oc_appconfig WHERE appid="market" AND configkey="key" ;
Query OK, 1 row affected (0.005 sec)
```

**Comment by micbar** [comment]
fixed with #871

**Comment by micbar** [comment]
Release 0.6.2 is already published.

**Comment by mraumala-roku** [comment]
Just wondering how many ownCloud hosts could be stuck with the Market 0.6.1 
because of they can't upgrade to 0.6.2 due to the Market backend rejecting 
the keyless "Authorization: apikey: " header.
