### ISSUE TITLE
ZimbraDrive not compatible with latest NextCloud/OwnCloud

### ISSUE THREAD

**Issue by ronbass** [owncloud/market#495]
HI,
There was no place where I could find any information about any issue for the market app of Zimbradrive for Owncloud 10.2.1 (or NextCloud).
I wasted hours trying to fix my Owncloud server after I upgraded it from 10.1 to 10.2 not knowing it was this issue then found that the Zimbradrive version is not compatible with it and it disappeared as well from the Owncloud Market menu in the server but is still offered on https://marketplace.owncloud.com/apps/zimbradrive -v.0.8.22
I downloaded this version but got the same error:
Zimbra Drive 0.8.23 by ZeXtras (AGPL-licensed)
This app cannot be installed because the following dependencies are not fulfilled:
ownCloud 10.0 or lower is required.

I would not have upgraded my server if I knew I would lose Zimbradrive as it is important for my Zimbra email server, now users lost their access to their drive files and I am stuck with it as I cannot downgrade Owncloud!
Will there be any update very soon?
Thank you

**Comment by phil-davis** [comment]
I made PR https://github.com/ZeXtras/zimbra-drive/pull/41 to bump the owncloud max-version.
I do not see why the app has been restricted to owncloud 10.0.* only.

**Comment by ronbass** [comment]
Hi Phil,
Sorry but I did not notice the correction you made in info.xml.
I rectified the line and all is working fine now, thank you so much.

**Comment by ronbass** [comment]
Although it worked but produced an integrity check error.

**Comment by phil-davis** [comment]
The app will need a new release, which will get a new checksum calculation and singing and...
That is not within my powers. If the Zimbra people do not respond, then their app is dead.

**Comment by ronbass** [comment]
Hi @phil-davis I left a message on the other comments, it was finally updated and all is working fine with OwnCloud.
Thank you
