### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#5]
Please add a Makefile which installs the dependencies.

Ideally, `make dist` would build a releasable version (cleant up) in a subdir "build" or "dist" in which the release script can pick it up.

**Comment by PVince81** [comment]
I can take care of this once I get the set of commands from @felixheidecke required to build the minified/concatenated bundle.

**Comment by PVince81** [comment]
https://github.com/owncloud/market/wiki/Frontend-development-(WIP)

**Comment by DeepDiver1975** [comment]
done
