### ISSUE TITLE
Update market app through marketplace

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#52]
Idea: provide updates for the market app through the marketplace.

Every release would still bundle the latest version of the market app.
Subsequent non-bundled releases can then be published in the marketplace itself so instances could update it.

There is some risk associated because if the updated market app is broken, no more online update is possible. Also, self-updating code can be tricky.

Setting to backlog, needs discussion.

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
Technically this is possible but needs careful testing ...

**Comment by DeepDiver1975** [comment]
Tested - works -> close
