### ISSUE TITLE
Hard-coded absolute paths in build

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#55]
```
~/temp/owncloud-10.0.0RC4/apps/market/js
  % grep -re checkout * 
Component.options.__file = "/home/sign/administration-internal/release-scripts/temp-checkout473751/market/src/components/Rating.vue"
Component.options.__file = "/home/sign/administration-internal/release-scripts/temp-checkout473751/market/src/App.vue"
Component.options.__file = "/home/sign/administration-internal/release-scripts/temp-checkout473751/market/src/components/Details.vue"
Component.options.__file = "/home/sign/administration-internal/release-scripts/temp-checkout473751/market/src/components/List.vue"
Component.options.__file = "/home/sign/administration-internal/release-scripts/temp-checkout473751/market/src/components/Navigation.vue"
Component.options.__file = "/home/sign/administration-internal/release-scripts/temp-checkout473751/market/src/components/Tile.vue"
```

Strangely the tarball works on one instance and the market app loads properly.
But in another instance I get JS errors:
![market-js-error](https://cloud.githubusercontent.com/assets/277525/25377288/6b35283c-29a7-11e7-9ab6-c1b84347b3fc.png)

@felixheidecke please fix the absolute paths issue. I hope this won't require a full retesting of the app.

I'll try and find out why one instance works fine but not the other.

**Comment by PVince81** [comment]
The original of my issue is because I installed the guests app: https://github.com/owncloud/guests/issues/51

So now all that remains is the hard-coded paths, less critical. Setting to high.

**Comment by felixheidecke** [comment]
These paths are only generated while in dev mode. The issue was fixed with the introduction of a proper production-build script.
