### ISSUE TITLE
Cannot rate apps in market

### ISSUE THREAD

**Issue by davitol** [owncloud/market#56]
Stars rating does not work

![screen shot 2017-04-25 at 12 08 32](https://cloud.githubusercontent.com/assets/10596560/25380279/07cc0d70-29b0-11e7-9910-ec6803a59b7e.png)

**Comment by DeepDiver1975** [comment]
it is not planned to rate an app in here - people need to go to the marketplace to rate.
rating requires to 'buy' the app. the whole purchase process is within the marketplace and has to stay there.

maybe we shall provide a link to the app in the marketplace @felixheidecke

**Comment by felixheidecke** [comment]
> maybe we shall provide a link to the app in the marketplace @felixheidecke

If the API can provide the propper URL, I will implement that :-)

**Comment by DeepDiver1975** [comment]
As explained:  rating requires the purchase workflow which will not be part of the market.
