### ISSUE TITLE
market 0.5.1

### ISSUE THREAD

**Issue by IljaN** [owncloud/market#582]
A problem we encountered: 

For users which have old owncloud 10.4 with market app 0.5.0 we need an intermediate market app release (0.5.1) which prompts the user to upgrade to core 10.5 to use the new trial-process. ownCloud 10.5 has market app 0.6.0 which is incompatible to 10.4

**Comment by jnweiger** [comment]
@IljaN is this a blocker for the 10.5.0 final release?

**Comment by IljaN** [comment]
No don't think so.

**Comment by HanaGemela** [comment]
It's a blocker for 10.5 release
@IljaN please do the dev work

**Comment by IljaN** [comment]
Branch created from tag 0.5.0 https://github.com/owncloud/market/pull/586

**Comment by HanaGemela** [comment]
### Reason

- Release needed for "ticket X", "feature Y"

### Product approval

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [ ] Generate Changelog
- [ ] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [ ] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [ ] Bump version in `info.xml` (no version suffix)
- [ ] Check php version dependency in `info.xml`
- [ ] Check minimum ownCloud version dependency in `info.xml`
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] Create github tag for `v${version}RC1` on release branch
- [ ] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [ ] Rename last RC tarball to final
- [ ] Create github tag for final `v${version}` on release branch
- [ ] Upload as Github release using changelog entries

### Publishing

- [ ] Upload tarball to marketplace (see handbook for details)
- [ ] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Rename QA milestone to `$version`
- [ ] Add a new 'Unreleased' section in CHANGELOG.md
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [ ] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol https://github.com/owncloud/market/releases/tag/v0.5.1RC2

**Comment by davitol** [comment]
## How it was tested.

1- In a 10.4.1 oC server with market app 0.5.0 upgrade market app via CLI using the tarball `occ market:install -l /mnt/data/files/admin/files/market-0.5.1RC2.tar.gz`
2- In market app, click on Start Enterprise Trial Button

<img width="706" alt="Screenshot 2020-07-28 at 16 22 33" src="https://user-images.githubusercontent.com/10596560/88681092-7d884600-d0f1-11ea-8244-1ec7b470a08f.png">


Also market app was sanity tested and checked the min/max versions in `appinfo.xml` file

**Comment by HanaGemela** [comment]
Final ready in GitHub waiting for deployment of marketplace to be published publicly 
https://github.com/owncloud/market/releases/tag/v0.5.1
