### ISSUE TITLE
Market app changes the styles of the new owncloud enterprise trial popup

### ISSUE THREAD

**Issue by davitol** [owncloud/market#588]
## How it looks like in market view:

<img width="710" alt="Screenshot 2020-07-29 at 09 55 18" src="https://user-images.githubusercontent.com/10596560/88777376-6eec6e00-d187-11ea-974a-237d442256d7.png">

## How it looks like in files view:

<img width="687" alt="Screenshot 2020-07-29 at 10 03 50" src="https://user-images.githubusercontent.com/10596560/88777651-bf63cb80-d187-11ea-9ac8-8328a7979424.png">

**Comment by DeepDiver1975** [comment]
can be ignored from my pov ....
