### ISSUE TITLE
Market is not shown using Safari as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/market#59]
![screen shot 2017-04-25 at 12 26 47](https://cloud.githubusercontent.com/assets/10596560/25381006/82af2188-29b2-11e7-8799-df21c9eec795.png)

Safari version: Version 9.1.2 (10601.7.7)

**Comment by felixheidecke** [comment]
Is this code from the production build or dev?

**Comment by davitol** [comment]
@felixheidecke From owncloud-10.0.0RC4.tar.bz2

**Comment by felixheidecke** [comment]
Pls wait for RC5. The build process has been changed.

**Comment by davitol** [comment]
I have also tested in RC5 and it keeps failing

![screen shot 2017-04-26 at 10 12 06](https://cloud.githubusercontent.com/assets/10596560/25424528/df5e50be-2a68-11e7-87e0-96959256782f.png)

**Comment by tomneedham** [comment]
master works now on safari, after running `make` and `npm run build`
