### ISSUE TITLE
Pending Bumps and Security Fixes

### ISSUE THREAD

**Issue by mmattel** [owncloud/market#620]
There are a bunch of pending Bumps and Security fixes.
Except one where there are conficts, for all others I have rebased.
CI and Sonarcloud are green, but it are waiting for codecov AND the bot has not signed the CLA...

Note: it seems that the Oracle pwd will expire soon...
```
1 | latest: Pulling from owncloudci/oracle-xe
-- | --
2 | Digest: sha256:81dd208da427f5750ca30e6b86f2bd5c43c466d7ca3e2b832572f34877cfcfdd
3 | Status: Downloaded newer image for owncloudci/oracle-xe:latest
4 | Starting Oracle Net Listener.
5 | Starting Oracle Database 11g Express Edition instance.
6 |  
7 | ERROR:
8 | ORA-28002: the password will expire within 7 days
```

@micbar and @phil-davis can you take a look on to find a solution so that can get approved and merged?

**Comment by phil-davis** [comment]
codecov is no longer a required CI result.

@micbar there are lots of dependabot PRs for dependency bumps. In some of them the bot has put [Security] - but I have no idea if the security patches are directly relevant to us. IMO it will be easiest if someone gets all the dependency updates merged, and make a new release. But who is the "someone" who should manage this app?

**Comment by phil-davis** [comment]
@micbar there is a long list of version-bump PRs for Javascript stuff. Who is supposed to look after those?

**Comment by micbar** [comment]
I am no longer working in that oc10 context for years. Unassigning myself.
