### ISSUE TITLE
Release attr. missing if App is installed

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/market#63]
API returns an empty `release` attribute for installed apps, but **version#** and **license** should remain for installed apps as well!

**Comment by IljaN** [comment]
@felixheidecke Can you please post a example reqeust url, I am currently a noob in api things ;)

**Comment by felixboehm** [comment]
Found this in the code: https://github.com/owncloud/market/blob/master/lib/Controller/MarketController.php#L148

**Comment by felixheidecke** [comment]
Release data is moved to InstallInfo after installing.
