### ISSUE TITLE
Elements of market doesn't limit the preview text.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/market#65]
Some apps can have a long text and it wont appear nicely when showing the available apps from marketplace.

![screen shot 2017-05-04 at 14 41 53](https://cloud.githubusercontent.com/assets/9048796/25703962/00d3ef22-30d8-11e7-9ff1-f8c6204ea9d2.png)

**Comment by felixheidecke** [comment]
Has been fixed in 10.0.1

**Comment by SergioBertolinSG** [comment]
Confirmed in 10.0.2rc1. There is weird fade out before entering categories:

![may-30-2017 09-10-04](https://cloud.githubusercontent.com/assets/9048796/26571838/f0c95640-4517-11e7-8bc2-5019a6ea9ee1.gif)

**Comment by felixheidecke** [comment]
> There is weird fade out before entering categories, is it intended?

Japp, it's not the best but its something I came up with on short notice.
