### ISSUE TITLE
[strictly 10.8.0]  Market 0.6.1

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/market#651]
# Release 0.6.1

### Needed for:

- Use relative URLs instead of absolute URLs in Notifications https://github.com/owncloud/market/pull/650
### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) -> Changelog testing, no Testplan needed 
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump version in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [ ] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Tested #650 manually
    - [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [ ] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10-0)  and [new portal](https://portal.owncloud.com) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by micbar** [comment]
RC in https://github.com/owncloud/market/releases/tag/v0.6.1RC1

**Comment by JanAckermann** [comment]
| Test Case                                | Expected Result                          | Result Master  | Result Stable10 | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- | --------------- |
| Enable market app. Login as admin user and regular user. | Admin user can see cart icon in the left menu and can be accessed. Regular user cannot see cart icon and cannot access market. | :construction: | :construction:  |                 |
| Check that left and right menus are following the css style of the rest of oC server |                                          | :construction: | :construction:  |                 |
| Check that the connection with the marketplace is working and the list of apps is being retrieved. |                                          | :construction: | :construction:  |                 |
| Install one community app previously included with owncloud. (user_ldap, activity,  gallery, etc) | There is no problem with installation. (If there are problems try with another, here we are testing the market app, not the actual app installed) | :construction: | :construction:  |                 |
| Follow the enterprise trial process to convert a community edition server into an enteprise edition one. https://marketplace.owncloud.com/enterprise-trial | The process is smooth and as result you get a working EE instance. | :construction: | :construction:  |                 |
| Use occ market:list                      | A list of the existing apps in the marketplace appears. | :construction: | :construction:  |                 |
| Use occ market:install {choose an app from the previous list} | The app is installed correctly.          | :construction: | :construction:  |                 |
| 1. Download the code from marketplace of an app of your choice like a tar.gz file. 2. Use occ market:install --local=AppCode.tar.gz | The app is installed correctly.          | :construction: | :construction:  |                 |
| 1. Download the code from marketplace of an app of your choice with several versions available like a tar.gz file, get the oldest version available. Also download the newest version. 2. Use occ market:install --local=App.oldVersion.tar.gz 3. Run occ market:upgrade --local=App.newVersion.tar.gz | The app is updated correctly.          | :construction: | :construction:  |                 |
| Check that the web ui elements work fine using Safari |                                          | :construction: | :construction:  |                 |
| Check that the web ui elements work fine using IE 11 |                                          | :construction: | :construction:  |                 |
| Check that the web ui elements work fine using Edge |                                          | :construction: | :construction:  |                 |
| Check that the web ui elements work fine using Firefox |                                          | :construction: | :construction:  |                 |
| Check that the web ui elements work fine using Chrome |                                          | :construction: | :construction:  |                 |
| Having installed one app from the marketplace, uninstall it using the webui, reinstall it again |  The app is uninstalled correctly and installed again without problems.                                         | :construction: | :construction:  |                 |

**Comment by jnweiger** [comment]
Download:    https://github.com/owncloud/market/releases/tag/v0.6.1
Marketplace: https://marketplace.owncloud.com/apps/market
