### ISSUE TITLE
App fails to install but UI says 'installed'

### ISSUE THREAD

**Issue by tomneedham** [owncloud/market#71]
- Opened the market app
 - Tried to install user_ldap
 - Network tab shows:
`{"error":true,"message":"An exception occurred while executing 'CREATE TABLE `oc_ldap_user_mapping` (`ldap_dn` VARCHAR(255) DEFAULT '' NOT NULL, `owncloud_name` VARCHAR(255) DEFAULT '' NOT NULL, `directory_uuid` VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX ldap_dn_users (`ldap_dn`), PRIMARY KEY(`owncloud_name`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ldap_user_mapping' already exists"}`
 - UI Shows:
![screen shot 2017-05-09 at 12 21 51](https://cloud.githubusercontent.com/assets/660805/25846438/190aca38-34b2-11e7-986e-772becf12b17.png)

**Comment by felixheidecke** [comment]
Fixed in https://github.com/owncloud/market/pull/67
