### ISSUE TITLE
Display an application's version information

### ISSUE THREAD

**Issue by settermjd** [owncloud/market#72]
Recently, while attempting to report an issue about the Custom Groups marketplace application, it would have been handy to see the application's version information, when viewing the details of the application from the market integration within ownCloud (below), instead of having to get it from the marketplace.

Can the version be added to the app's meta information, alongside its category (or somewhere else, nearby) please?

![app version meta information](https://cloud.githubusercontent.com/assets/196801/25887330/06714ae0-3562-11e7-8763-6027359cb0e9.png)

**Comment by felixheidecke** [comment]
This relates to https://github.com/owncloud/market/issues/63
Ping @DeepDiver1975
