### ISSUE TITLE
Add ability to install bundles

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#74]
- list/search bundles (special separate API)?
- install bundle
- uninstall bundle ? (optional, not sure if needed)

@DeepDiver1975

**Comment by PVince81** [comment]
will also likely need its own section in the UI @felixheidecke to think about design

**Comment by PVince81** [comment]
Needs to work both in web UI and CLI.

Do bundles need to be a separate concept on the CLI or are bundles just like regular app package names ?

In the zypper world (openSUSE), there is a difference between a distro package and "patterns" which are groups of packages. Installing these require different switches on the CLI.

To keep it simple I'd suggest to not expect specific switches and simply allow bundles to have ids like app ids. But this implies that the marketplace prevents app id and bundle id conflicts. Is that the case ?

**Comment by PVince81** [comment]
@VicDeo please work on the backend for this + CLI interface. You can talk with @IljaN for the marketplace side APIs.

@felixheidecke please take care of the market app frontend.

**Comment by VicDeo** [comment]
@PVince81 Is there any bundle spec?  I recall that I saw it somewhere already but not sure.

**Comment by PVince81** [comment]
I don't know, talk with the marketplace people @IljaN

**Comment by felixboehm** [comment]
I think installing a bundle via cli will be quite similar to installing an app.
The tar coming from marketplace just contains multiple apps. An app might also be a theme, but in app format.
So just unpack and move everything to the apps folder.
@IljaN is that correct?

**Comment by PVince81** [comment]
unpacking and move is not enough, there are processes to set in motion by calling core functions for each app to trigger installation/migrations.

**Comment by VicDeo** [comment]
@felixboehm according to our short chat discussion a draft bundle implementation will provide a list of separate links instead of a single package.

**Comment by IljaN** [comment]
Bundled download in a single tar is not possible as we store the tar files on the serverside, we would need to dynamically repackage all the bundled app tars to a single one dynamically on download.

**Comment by PVince81** [comment]
> a list of separate links instead of a single package.

Somehow I'm picturing an XML or JSON package file (like package.json?) containing a list of apps to download.

Any decision on the detailed spec?

**Comment by DeepDiver1975** [comment]
to me a bundle is just a list of apps which belong together for one major version of owncloud.
there is nothing like a version dependency to the bundle - dependencies are within the apps.
once a user installs a bundle and one of the apps doesnt meet the requirements we skip to the next app.

please keep in mind that now only the platform version is a requirement to check against but also databases, php modules, php version and may more.

we have to keep this to the app level.

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo isn't this solved already ? close ?

**Comment by VicDeo** [comment]
@PVince81 I've just ordered an enterprise trial and installed bundled apps with a single click.
Implemented.
