### ISSUE TITLE
Button "install" -> "installed" after installation

### ISSUE THREAD

**Issue by voroyam** [owncloud/market#79]
If I install an app, for example the calendar app, I see the picture and 2 buttons, update and install.

Install is in blue. I click on install, the page reloads and now the button for install is white.

Should the button now say "installed" ?

![](https://cloud.githubusercontent.com/assets/24212810/26241485/225e7172-3c85-11e7-8248-fe189856208e.png)

**Comment by felixheidecke** [comment]
Please check your version. These two buttons shouldn't appear in the current version.
If you are checking this out from Github, make sure to `npm run build`.
