### ISSUE TITLE
Install missing bundled apps that were moved to market

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#8]
In the future we will want to move more and more bundled apps to the market.

The problem with this is that when the user updates core (tarball/updater/distro package), an app that was present before on the filesystem is now missing because it's not in the bundle any more.

Some apps MUST be enabled at `occ upgrade` time especially ones with user backends to make sure that all users get covered by repair steps.

So the goal is to have the market hook into the upgrade process and check which app is market as enabled in `oc_appconfig` but where the code is missing. For the missing apps, install the market version of these apps.

The challenge will likely be that such apps have no OCS ID currently, so we might need to bundle a hard-coded list of apps that we knew were bundled but aren't any more in a way that the market can find and reinstall them.

Raised here instead of updater because I think this could also affect tarball users.

@DeepDiver1975 @VicDeo please comment

**Comment by DeepDiver1975** [comment]
> The challenge will likely be that such apps have no OCS ID currently, so we might need to bundle a hard-coded list of apps that we knew were bundled but aren't any more in a way that the market can find and reinstall them.

the ocsid is mandatory for apps which are accessible via the marketplace.

**Comment by PVince81** [comment]
So we'll need a mapping between ocsid less bundled apps from 9.1 and their new ocsid in the market for the transitional phase

**Comment by DeepDiver1975** [comment]
> So we'll need a mapping between ocsid less bundled apps from 9.1 and their new ocsid in the market for the transitional phase

yes

**Comment by PVince81** [comment]
Assigning to you since you're working on the market @DeepDiver1975

**Comment by DeepDiver1975** [comment]
well - the new marketplace could live without the ocsid ....

**Comment by PVince81** [comment]
Do apps have a different kind of id then ? Can people rename apps ?

**Comment by DeepDiver1975** [comment]
The app id is used in the cert used for signing.
We have full controll who is developing which appears.

**Comment by PVince81** [comment]
Maybe use shipped.json as mapping file. Basically move the app into a new section and point it at the market app if.

So when the update code runs, it checks that section and can fetch the app from the market.

How about apps like calendar/contacts ?

**Comment by PVince81** [comment]
map old ocs id to market id somehwere ?

**Comment by PVince81** [comment]
quoting @DeepDiver1975 

> well - we can rely on the id of the market - the id is the folder name - which is the unique name on the marketplace as well

**Comment by PVince81** [comment]
1. get all local apps
2. check if there is a more recent version in the market place
3. if yes, download and install it with the market APIs

Also need an alternative way of updating with tarballs for offline instances: https://github.com/owncloud/market/issues/19

**Comment by PVince81** [comment]
@VicDeo where are we with this ?

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo any update here ?

So far we haven't moved any app to the market. If we don't move any for 10.0 then this is less urgent but will still need to be done once we start moving stuff...

cc @felixboehm

**Comment by felixboehm** [comment]
needs documentation https://github.com/owncloud/documentation/issues/3011

**Comment by PVince81** [comment]
we're going to move user_ldap to the market, so this needs to be in 10.0.

Closing in favor of https://github.com/owncloud/market/issues/39 which contains the agreed on update workflow
