### ISSUE TITLE
Output entries for when downloading and installing apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#80]
Because else it just sits there for a while and the admin doesn't know what it's doing.

Also, have this visible without requiring `-vvvv`

@VicDeo 

cc @butonic

**Comment by butonic** [comment]
àfter turned on maintenance mod it executes tons of repair steps ...

**Comment by VicDeo** [comment]
@PVince81 it's a core thing. Repair step can use either `info` or `warning` right now
https://github.com/owncloud/core/blob/master/lib/public/Migration/IOutput.php

`info` isn't shown in non-verbose mode while `warning` is red and brutal.

**Comment by PVince81** [comment]
doesn't matter where the fix needs to go...

**Comment by butonic** [comment]
in general I would prefer to run the occ commands very verbose by default and add a quiet option if you really want no output. Personally, I hate the progressbars with a passion. They hide all the useful information: which user is it syncing, which file is it scanning. I don't want to run the command twice to hope it fails exactly the same way when adding debug output ...

**Comment by patrickjahns** [comment]
This should be handled by these two prs in core:

https://github.com/owncloud/core/pull/28876 
https://github.com/owncloud/core/pull/28813

Also #143 should help with defining `<error>` tags for symfony console output
