### ISSUE TITLE
Remove files menu for regular users

### ISSUE THREAD

**Issue by davitol** [owncloud/market#82]
![screen shot 2017-05-22 at 08 59 23](https://cloud.githubusercontent.com/assets/10596560/26296206/ef0520c8-3ecd-11e7-8a7c-ace702acecd2.png)

If a regular user can only access to files, then it is useless this menu

**Comment by DeepDiver1975** [comment]
How is this related to the market app?
If there is only files - we have only files in there?

**Comment by davitol** [comment]
@DeepDiver1975 My fault, i opened it here thinking about market icon... I will reopen it in core repo
