### ISSUE TITLE
App description can be markdown

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/market#92]

**Comment by hurradieweltgehtunter** [comment]
FE needs to parse it.
@felixheidecke
import marked from 'marked'
-> marked(rawText, { sanitize: true })

**Comment by DeepDiver1975** [comment]
are you sure with the usage of marked? the development doesn seem that active .... I did choose showdown.js in core ...

**Comment by hurradieweltgehtunter** [comment]
i'm using it in marketplace FE. Works fine so far

**Comment by DeepDiver1975** [comment]
> i'm using it in marketplace FE. Works fine so far

im aware of that - all I'm saying is that the marked project is not that well maintained compared to showdown from my understanding. and this is a criteria to think about

**Comment by hurradieweltgehtunter** [comment]
indeed. and it's much more customizable. will implement
issue: https://github.com/owncloud/marketplace/issues/400

**Comment by settermjd** [comment]
This seems like the right place to mention this (I may be wrong). In the market app, the description, if provided in Markdown format, doesn't render correctly as HTML. The example in the screenshot shows the description of the OAuth2 app not rendering as HTML. However, the same description does render correctly when viewed on the Marketplace.

![app-description-markdown-doesnt-render](https://user-images.githubusercontent.com/196801/31658318-f9bfdddc-b330-11e7-8f30-21c79f952ea7.png)
