### ISSUE TITLE
"Shipped apps cannot be uninstalled" for enterprise_key

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/market#94]
The following scenario:

If you installed the *enterprise_key* App because you had a trail version running and the demo ran out, you can't uninstall the Key App. Thre response is: **"Shipped apps cannot be uninstalled"**

**Comment by DeepDiver1975** [comment]
:omg:

**Comment by DeepDiver1975** [comment]
we need to fix this as well ...

**Comment by DeepDiver1975** [comment]
fixed in core
