### ISSUE TITLE
Fixes - release critical

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/market#96]
- [x] after installing /apps gets called 10 times with the same result. Reduce to one request
![image](https://user-images.githubusercontent.com/16665512/27630321-6b36dcba-5bf5-11e7-87c4-fe70c680f4a4.png)

- [x] Rename "App-Zusammenstellungen" to "Bundles"
- [x] App detail page: description is not shown. Only summary is displayed.

# development
- [x] merge open PRs for release @felixheidecke 

# qa 
- [x] testing the market app @hurradieweltgehtunter @felixheidecke 

# release
- [x] build, sign @DeepDiver1975 
- [x] upload to marketplace @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Rename "App-Zusammenstellungen" to "Bundles"

https://www.transifex.com/owncloud-org/owncloud/translate/#de/market/114756172

**Comment by hurradieweltgehtunter** [comment]
> https://www.transifex.com/owncloud-org/owncloud/translate/#de/market/114756172

can't access

**Comment by felixheidecke** [comment]
Moved non critical tasks to: https://github.com/owncloud/market/issues/116
